export const PROJECT_MARKERS: Array<{ file: string; kind: string }> = [
  { file: "package.json", kind: "node" },
  { file: "bun.lock", kind: "bun" },
  { file: "bun.lockb", kind: "bun" },
  { file: "package-lock.json", kind: "npm" },
  { file: "pnpm-lock.yaml", kind: "pnpm" },
  { file: "yarn.lock", kind: "yarn" },
  { file: "Cargo.toml", kind: "rust" },
  { file: "go.mod", kind: "go" },
  { file: "pyproject.toml", kind: "python" },
  { file: "requirements.txt", kind: "python" },
  { file: "Pipfile", kind: "python" },
  { file: "composer.json", kind: "php" },
  { file: "Gemfile", kind: "ruby" },
  { file: "pom.xml", kind: "java" },
  { file: "build.gradle", kind: "java" },
  { file: "build.gradle.kts", kind: "java" },
  { file: "Dockerfile", kind: "docker" },
  { file: "docker-compose.yml", kind: "compose" },
  { file: "docker-compose.yaml", kind: "compose" },
  { file: "compose.yaml", kind: "compose" },
  { file: "compose.yml", kind: "compose" },
  { file: "Makefile", kind: "make" },
  { file: "mix.exs", kind: "elixir" },
  { file: "deno.json", kind: "deno" },
  { file: "deno.jsonc", kind: "deno" },
];

export const FRAMEWORK_FILES: Array<{ file: string; name: string }> = [
  { file: "vite.config.ts", name: "Vite" },
  { file: "vite.config.js", name: "Vite" },
  { file: "vite.config.mjs", name: "Vite" },
  { file: "next.config.js", name: "Next.js" },
  { file: "next.config.mjs", name: "Next.js" },
  { file: "next.config.ts", name: "Next.js" },
  { file: "nuxt.config.ts", name: "Nuxt" },
  { file: "nuxt.config.js", name: "Nuxt" },
  { file: "astro.config.mjs", name: "Astro" },
  { file: "astro.config.ts", name: "Astro" },
  { file: "remix.config.js", name: "Remix" },
  { file: "svelte.config.js", name: "SvelteKit" },
  { file: "angular.json", name: "Angular" },
  { file: "manage.py", name: "Django" },
  { file: "config/routes.rb", name: "Rails" },
  { file: "artisan", name: "Laravel" },
  { file: "nest-cli.json", name: "Nest" },
];

export const MAX_ANCESTOR_WALK = 8;
